version: '3'

services:
  pgdb:
    image: postgres
    container_name: pg-server-user-01
    ports:
      - '5550:5431'
    environment:
      - POSTGRES_USER=codecampuser
      - POSTGRES_PASSWORD=codecampuserP
      - POSTGRES_DB=CodecampUserDB
    volumes:
      - ./docker/pg/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/pg:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge