version: '3'

services:
  codecamp-database:
    image: postgres
    container_name: codecamp_db_01
    ports:
      - '5550:5432'
    environment:
      POSTGRES_DB: codecampDB
      POSTGRES_USER: codecamp123
      POSTGRES_PASSWORD: codecamp123P
    volumes:
      - ./docker/pg/postgres.conf:/etc/postgresql/postgresql.conf
#      - ./data/pg:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - postgres
    restart: always

  pgadminFp:
    image: dpage/pgadmin4
    container_name: pgadmin_01
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_SERVER_JSON_FILE: /tmp/.pgadmin/servers.json
    volumes:
      - ./data/pgadmin:/tmp/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge