version: '3'

services:
  pgdb:
    image: postgres
    container_name: pg-server-assignment-01
    ports:
      - '5550:5432'
    environment:
      - POSTGRES_USER=codecampassignment
      - POSTGRES_PASSWORD=codecampassignmentP
      - POSTGRES_DB=codecampassignmentDB
    volumes:
      - ./docker/pg/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/pg:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge